apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-required
spec:
  replicas: 3

  selector:
    matchLabels:
      app: affinity-required

  template:
    metadata:
      labels:
        app: affinity-required

    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: In
                values:
                - primary

      containers:
      - name: nginx
        image: nginx